# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Minimal"
license = "Creative Commons Attribution-ShareAlike 3.0 Unported License"
licenselink = "http://creativecommons.org/licenses/by-sa/3.0/"
description = ""
homepage = ""
tags = ["minimal", "blog"]
features = [ "responsive" ]
min_version = 0.34

[author]
  name = "Russell Hay"
  homepage = "https://github.com/RussTheAerialist"

# If porting an existing theme
[original]
  name = "minimal"
  homepage = "http://orderedlist.github.com/minimal/"
